spring.application.name=ProductService
spring.data.mongodb.uri=mongodb+srv://modelo_prueba_test_admi:8QVlUA1MSVuq9MjZ@cluster0.ovvknir.mongodb.net/product_db
spring.kafka.bootstrap-servers=kafka:29092